---
dependency:
  name: galaxy
  options:
    requirements-file: ../../roles/requirements.yml
    role-file: ../../roles/requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

# NOTE: Molecule >= 25 removed the built-in `lint` command.
# Linting is now expected to be run separately (e.g. `yamllint .` and `ansible-lint`).
# The previous inline lint block was removed to avoid ModuleNotFoundError: molecule.command.lint.
# This scenario name is retained for continuity; it now focuses on syntax + converge + verify.

platforms:
  - name: localhost
    groups:
      - local

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      stdout_callback: default
      result_format: yaml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: auto_silent
    host_vars:
      localhost:
        ansible_connection: local
  playbooks:
    converge: converge.yml
    verify: verify.yml
    prepare: prepare.yml

verifier:
  name: ansible

scenario:
  name: with-linting
  test_sequence:
    - syntax
    - prepare
    - converge
    - verify
