---
# Molecule prepare playbook for with-linting scenario

- name: Prepare test environment
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Verify Python environment
      ansible.builtin.debug:
        msg: "Python interpreter: {{ ansible_playbook_python }}"

    - name: Verify roles directory exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../../roles/ans_dev_sandbox_role"
      register: role_dir
      failed_when: not role_dir.stat.exists
